STAEFormer:
  didi:
    num_nodes: 400
    in_steps: 12
    out_steps: 12

    train_size: 0.6
    val_size: 0.2

    time_of_day: True
    day_of_week: True

    lr: 0.001
    weight_decay: 0.0015
    milestones: [25, 45, 65]
    lr_decay_rate: 0.1
    batch_size: 16
    max_epochs: 15
    early_stop: 10
    use_cl: False
    cl_step_size: 2500

    model_args:
      num_nodes: 400
      in_steps: 12
      out_steps: 12
      steps_per_day: 288
      input_dim: 3
      output_dim: 1
      input_embedding_dim: 16
      tod_embedding_dim: 16
      dow_embedding_dim: 16
      spatial_embedding_dim: 0
      adaptive_embedding_dim: 40
      feed_forward_dim: 256
      num_heads: 4
      num_layers: 3
      dropout: 0.1

  METRLA:
    num_nodes: 207
    in_steps: 12
    out_steps: 12

    train_size: 0.7
    val_size: 0.1

    time_of_day: True
    day_of_week: True

    lr: 0.001
    weight_decay: 0.0003
    milestones: [20,30]
    lr_decay_rate: 0.1
    batch_size: 16
    max_epochs: 200
    early_stop: 30
    use_cl: False
    cl_step_size: 2500

    model_args:
      num_nodes: 207
      in_steps: 12
      out_steps: 12
      steps_per_day: 288
      input_dim: 3
      output_dim: 1
      input_embedding_dim: 24
      tod_embedding_dim: 24
      dow_embedding_dim: 24
      spatial_embedding_dim: 0
      adaptive_embedding_dim: 80
      feed_forward_dim: 256
      num_heads: 4
      num_layers: 3
      dropout: 0.1


  PEMS04:
    num_nodes: 307
    in_steps: 12
    out_steps: 12

    train_size: 0.6
    val_size: 0.2

    time_of_day: True
    day_of_week: True

    lr: 0.001
    weight_decay: 0.0005
    milestones: [15, 30, 50]
    lr_decay_rate: 0.1
    batch_size: 16
    max_epochs: 300
    early_stop: 20
    use_cl: False
    cl_step_size: 2500

    model_args:
      num_nodes: 307
      in_steps: 12
      out_steps: 12
      steps_per_day: 288
      input_dim: 3
      output_dim: 1
      input_embedding_dim: 24
      tod_embedding_dim: 24
      dow_embedding_dim: 24
      spatial_embedding_dim: 0
      adaptive_embedding_dim: 80
      feed_forward_dim: 256
      num_heads: 4
      num_layers: 3
      dropout: 0.1

AR:
  didi:
    num_nodes: 16326
    in_steps: 12
    out_steps: 12
    milestones: [15, 30, 50]
    train_size: 0.6
    val_size: 0.2

    lr: 0.001
    batch_size: 16
    max_epochs: 20
    early_stop: 10
    use_cl: False
    cl_step_size: 2500

    model_args:
      p: 12
      num_nodes: 1000

MLP:
  didi:
    num_nodes: 16326
    in_steps: 12
    out_steps: 12
    milestones: [15, 30, 50]
    train_size: 0.6
    val_size: 0.2
    lr: 0.001
    batch_size: 16
    max_epochs: 20
    early_stop: 10
    use_cl: False
    cl_step_size: 2500

    model_args:
      hidden_dim: 64

Linear:
  didi:
    num_nodes: 16326
    in_steps: 12
    out_steps: 12
    milestones: [15, 30, 50]
    train_size: 0.6
    val_size: 0.2
    lr: 0.001
    batch_size: 16
    max_epochs: 20
    early_stop: 10
    use_cl: False
    cl_step_size: 2500

    model_args:
      input_dim: 1
  
Attention:
  didi:  
    num_nodes: 16326
    in_steps: 12
    out_steps: 12

    train_size: 0.6
    val_size: 0.2

    lr: 0.001
    weight_decay: 0.0015
    milestones: [25, 45, 65]
    lr_decay_rate: 0.1
    batch_size: 16
    max_epochs: 15
    early_stop: 10
    use_cl: False
    cl_step_size: 2500

    model_args:
      num_nodes: 16326
      in_steps: 12
      out_steps: 12
      steps_per_day: 288
      input_dim: 3
      output_dim: 1
      input_embedding_dim: 3
      feed_forward_dim: 256
      num_heads: 4
      num_layers: 3
      dropout: 0.1

DCST:
  didi:
    num_nodes: 400
    in_steps: 12
    out_steps: 12

    train_size: 0.7
    val_size: 0.1

    time_of_day: True
    day_of_week: True

    lr: 0.001
    weight_decay: 0.0003
    milestones: [20,30]
    lr_decay_rate: 0.1
    batch_size: 16
    max_epochs: 200
    early_stop: 10
    use_cl: False
    cl_step_size: 2500
    #clip_grad: 5

    model_args:
      num_nodes: 400
      in_steps: 12
      out_steps: 12
      steps_per_day: 288
      input_dim: 3
      output_dim: 1
      input_embedding_dim: 24
      tod_embedding_dim: 24
      dow_embedding_dim: 24
      spatial_embedding_dim: 0
      adaptive_embedding_dim: 80
      feed_forward_dim: 256
      num_heads: 4
      num_layers: 3
      dropout: 0.1


GWNet:
  didi:
    num_nodes: 6000
    in_steps: 12
    out_steps: 12

    train_size: 0.7
    val_size: 0.1

    time_of_day: True
    day_of_week: True

    lr: 0.001
    weight_decay: 0.0003
    milestones: [20,30]
    lr_decay_rate: 0.1
    batch_size: 16
    max_epochs: 20
    early_stop: 10
    use_cl: False
    cl_step_size: 2500
    #clip_grad: 5

    model_args:
      num_nodes: 6000
      gcn_bool: True
      addaptadj: True


SAGE:
  didi:
    num_nodes: 16326
    in_steps: 12
    out_steps: 12

    train_size: 0.7
    val_size: 0.1

    time_of_day: True
    day_of_week: True

    lr: 0.002
    weight_decay: 0.0001
    milestones: [20,30]
    lr_decay_rate: 0.1
    batch_size: 8
    max_epochs: 20
    early_stop: 10
    use_cl: False
    cl_step_size: 2500
  
    model_args:
      factors: 8
      layers: 5
      tem_patchsize: 12
      tem_patchnum: 1
      spa_patchsize: 4
      spa_patchnum: 4096
      node_num: 16326
      tod: 288
      dow: 7
      input_dims: 64
      node_dims: 32
      tod_dims: 32
      dow_dims: 32


AGCRN:
  didi:
    num_nodes: 1000
    in_steps: 12
    out_steps: 12

    train_size: 0.7
    val_size: 0.1

    time_of_day: True
    day_of_week: True

    lr: 0.001
    weight_decay: 0.0003
    milestones: [20,30]
    lr_decay_rate: 0.1
    batch_size: 16
    max_epochs: 20
    early_stop: 10
    use_cl: False
    cl_step_size: 2500

    model_args:
      num_nodes: 1000
      input_dim: 1
      output_dim: 1
      embed_dim: 10
      rnn_units: 64
      num_layers: 2
      cheb_k: 2


STID:
  didi:
    num_nodes: 16326
    in_steps: 12
    out_steps: 12

    train_size: 0.7
    val_size: 0.1

    time_of_day: True
    day_of_week: True

    lr: 0.001
    weight_decay: 0.0003
    milestones: [20,30]
    lr_decay_rate: 0.1
    batch_size: 16
    max_epochs: 20
    early_stop: 10
    use_cl: False
    cl_step_size: 2500
    
    model_args:
      num_nodes: 16326
      input_len: 12
      input_dim: 3
      embed_dim: 32
      output_len: 12
      num_layer: 3
      if_node: True
      node_dim: 32
      if_T_i_D: True
      if_D_i_W: True
      temp_dim_tid: 32
      temp_dim_diw: 32
      time_of_day_size: 288
      day_of_week_size: 7

PatchSTG:
  didi:
    num_nodes: 16326
    in_steps: 12
    out_steps: 12

    train_size: 0.7
    val_size: 0.1

    time_of_day: True
    day_of_week: True

    lr: 0.002
    weight_decay: 0.0001
    milestones: [20,30]
    lr_decay_rate: 0.1
    batch_size: 8
    max_epochs: 20
    early_stop: 10
    use_cl: False
    cl_step_size: 2500
    
    model_args:
      factors: 8
      layers: 5
      tem_patchsize: 12
      tem_patchnum: 1
      spa_patchsize: 4
      spa_patchnum: 4096
      node_num: 16326
      tod: 288
      dow: 7
      input_dims: 64
      node_dims: 32
      tod_dims: 32
      dow_dims: 32

PatchGCN:
  didi:
    num_nodes: 16326
    in_steps: 12
    out_steps: 12
    train_size: 0.7
    val_size: 0.1
    time_of_day: True
    day_of_week: True

    lr: 0.002
    weight_decay: 0.0001
    milestones: [20,30]
    lr_decay_rate: 0.1
    batch_size: 8
    max_epochs: 20
    early_stop: 10
    use_cl: False
    cl_step_size: 2500
  
    model_args:
      factors: 8
      layers: 5
      tem_patchsize: 12
      tem_patchnum: 1
      spa_patchsize: 4
      spa_patchnum: 4096
      node_num: 16326
      tod: 288
      dow: 7
      input_dims: 64
      node_dims: 32
      tod_dims: 32
      dow_dims: 32